#
# Makefile for SFI.
#

obj-$(CONFIG_EXYNOS_SFI_IPC)			+= sfi_ipc.o
obj-$(CONFIG_EXYNOS_SFI_CR52C1)			+= sfi_ipc_c1.o
obj-$(CONFIG_EXYNOS_SFI_IPC_TEST)		+= sfi_ipc_test.o
obj-$(CONFIG_EXYNOS_SFI_IPC_TEST_C1)		+= sfi_ipc_test_c1.o
obj-$(CONFIG_EXYNOS_SFI_CLI)			+= sfi_cli.o
obj-$(CONFIG_EXYNOS_SFI_CLI_C1)			+= sfi_cli_c1.o
obj-$(CONFIG_EXYNOS_SFI_DUMP)			+= sfi_dump.o
obj-$(CONFIG_EXYNOS_SFI_CLKMON)			+= sfi_clkmon.o





